# run: conda env create --file environment.yml
name: dash_env
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
- python>=3.8
- jupyter
- numpy
- matplotlib
- pandas
- tqdm
- dash
- jupyter-dash
- openpyxl
- dash-bootstrap-components

